# Generated by Django 5.2 on 2025-04-26 09:14

from decimal import Decimal

import core.models
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название/номер комнаты", max_length=100, unique=True
                    ),
                ),
                (
                    "price_per_day",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Стоимость комнаты за сутки",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "capacity",
                    models.IntegerField(
                        help_text="Колличесвто человек на которое расчитана комната",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_start", models.DateTimeField()),
                ("date_end", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.room",
                    ),
                ),
            ],
            options={
                "constraints": [
                    django.contrib.postgres.constraints.ExclusionConstraint(
                        expressions=[
                            (
                                core.models.TsTzRange(
                                    "date_start",
                                    "date_end",
                                    django.contrib.postgres.fields.ranges.RangeBoundary(),
                                ),
                                "&&",
                            ),
                            ("room", "="),
                        ],
                        name="exclude_overlapping_booking",
                    )
                ],
            },
        ),
    ]
