name: Run Pytest with Docker

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Installing pylint
      run: pip install pylint-django

    - name: Checking code
      run: pylint .
      

      
