name: Run Pytest

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: booking_app  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Pytest with coverage
      id: pytest
      run: |
        pytest
      continue-on-error: false  # не продолжать, если тесты не прошли

    - name: Reset repository on test failure
      if: failure()  # этот шаг выполняется, только если тесты не прошли
      run: |
        git reset --hard HEAD
        git clean -fd
        git push --force
